### ISSUE TITLE
Star types. 

### ISSUE THREAD

**Issue by ubernaut** [ubernaut/spaceSim#12]
OBAFGKM
https://en.wikipedia.org/wiki/Stellar_classification 

The type of star should influence the  intensity and type of radiation emitted by it. The radiation emitted could be represented by a bell shaped curve on the EM spectrum.

**Comment by fdesjardins** [comment]
- cc4c618094357f6e67fdb3429a47ddaddcf06813
- c175cdef4b97591fca88e43aabe45a9674968d76
